### ISSUE TITLE
Sample in .php

### ISSUE THREAD

**Issue by mofeejegi** [PaystackHQ/sample-charge-token-backend#1]
Understood the work going on in the tutorials, but I am not sure of how I'm to implement this. It would be really appreciated if an example can be done in .php, or at least, if further light can be thrown on this node.js sample

**Comment by ibrahimlawal** [comment]
Hey @hendy-ejegi try https://github.com/PaystackHQ/PaystackJS-Sample-code . It has the 2 routes required to do your sample backend

**Comment by mofeejegi** [comment]
Thanks so much.
